### ISSUE TITLE
Doesn't work on Linux systems without OpenSSL 1.1

### ISSUE THREAD

**Issue by slonopotamus** [asimmon/ephemeral-mongo#36]
OpenSSL 1.1 is [going EOL in September](https://www.openssl.org/blog/blog/2023/03/28/1.1.1-EOL/) and is being gradually removed from Linux systems:

1. Ubuntu 22.04 only has OpenSSL 3
2. Gentoo switched to OpenSSL 3 [last week](https://bugs.gentoo.org/899596)
3. Arch switched to OpenSSL 3 in Nov 2022

`mongod` bundled in EphemeralMongo simply doesn't start on such systems:

```
$ ~/.nuget/packages/ephemeralmongo6.runtime.linux-x64/1.1.0/runtimes/linux-x64/native/mongodb/bin/mongod 
/home/marat/.nuget/packages/ephemeralmongo6.runtime.linux-x64/1.1.0/runtimes/linux-x64/native/mongodb/bin/mongod: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
```

**Comment by ante-maric** [comment]
Oh man, I'm having the same issue :(

**Comment by asimmon** [comment]
I've just updated EphemeralMongo with the [latest available MongoDB](https://github.com/asimmon/ephemeral-mongo/releases/tag/1.1.2) community edition and the [CI is working well on Ubuntu 22.04 GitHub agents (`ubuntu-latest`)](https://github.com/asimmon/ephemeral-mongo/actions/runs/5434793636/jobs/9883580454) with MongoDB 4.4.22, 5.0.18 and 6.0.7.

**Comment by ante-maric** [comment]
> I've just updated EphemeralMongo with the latest available MongoDB community edition and the [CI is working well on Ubuntu 22.04 GitHub agents (`ubuntu-latest`)](https://github.com/asimmon/ephemeral-mongo/actions/runs/5434793636/jobs/9883580454) with MongoDB 4.4.22, 5.0.18 and 6.0.7.

Thank you very much for quick change! Unfortunately, I am still unable to get this working. If I run my tests that use mongo I get error: 

`MongoDB connection availability took longer than the specified timeout of 30 seconds. Consider increasing the value of 'ConnectionTimeout'. `

If I try to run mongod manually I get the same error as before:
`
./mongod: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory`

@slonopotamus  does the new version work for you?

**Comment by slonopotamus** [comment]
> does the new version work for you?

Nope. Binaries from ephemeralmongo 1.1.2 still depend on `libcrypto.so.1.1`:

```
$ ~/.nuget/packages/ephemeralmongo4.runtime.linux-x64/1.1.2/runtimes/linux-x64/native/mongodb/bin/mongod 
/home/marat/.nuget/packages/ephemeralmongo4.runtime.linux-x64/1.1.2/runtimes/linux-x64/native/mongodb/bin/mongod: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
```

**Comment by ante-maric** [comment]
I was looking at the dependencies list and saw both libcrypto.so.1.1 and libcrypto.so.3, but I thought maybe it is used depending on which version of Ubuntu you run it. Looking at the CI log that @asimmon posted it is run on Ubuntu 22.04 so I'm really confused.

**Comment by slonopotamus** [comment]
Well, GitHub Actions runners have LOTS of software installed besides base system.

**Comment by slonopotamus** [comment]
This (or just rolling back the the distro that still has OpenSSL 1.1) is OK as a temporary workaround, but not as a long-term solution because OpenSSL 1.1 will simply stop receiving updates and will turn into a security hole.

**Comment by asimmon** [comment]
If I try to simplify EphemeralMongo at its minimal expression, it's basically a zip that contains the `mongod` process downloaded from https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1804-6.0.7.tgz, and some optimized C# code that starts and the process.

You can manually try to run MongoDB on your servers, but it's not actually related to EphemeralMongo (unless the downloaded binary is the wrong one?).

**Comment by slonopotamus** [comment]
> downloaded from https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1804-6.0.7.tgz

That's the point.

`mongod` from https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1804-6.0.7.tgz depends on libcrypto.so.1.1
`mongod` from https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu2204-6.0.7.tgz depends on libcrypto.so.3

**Comment by ante-maric** [comment]
> > downloaded from https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1804-6.0.7.tgz
> 
> That's the point.
> 
> `mongod` from https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1804-6.0.7.tgz depends on libcrypto.so.1.1 `mongod` from https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu2204-6.0.7.tgz depends on libcrypto.so.3

Good catch! Then that is what needs to be packed into the nuget. Then we don't need to think about possible future security holes that you mentioned.

**Comment by slonopotamus** [comment]
I'm afraid that if you just _replace_ one `mongod` with another, we'll break things the other way: `mongod` will stop working on old distros that do not have `libcrypto.so.3`...

**Comment by ante-maric** [comment]
One solution would be to have separate nugets. Otherwise it all comes down to what is the most used distro.

**Comment by asimmon** [comment]
Thank you for your feedback, I really appreciate it. I anticipate this issue may become more frequent in the future as the adoption of Ubuntu 22.04 increases. That's why I am considering creating a new package targeting the `ubuntu.22.04-x64` .NET runtime identifier ([docs](https://learn.microsoft.com/en-us/dotnet/core/rid-catalog#linux-rids), [source](https://github.com/dotnet/runtime/blob/v7.0.0/src/libraries/Microsoft.NETCore.Platforms/src/runtime.json#L3990)). 

The new package would be named `EphemeralMongo6.runtime.ubuntu.22.04-x64`. It won't be a dependency of the all-in-one metapackage `EphemeralMongo6`. Developers will need to manually install this new package along with `EphemeralMongo.Core`.

**Comment by asimmon** [comment]
With the recent release of MongoDB 7, I took the opportunity to publish two new packages targeting Ubuntu 22.04, thus solving the OpenSSL compatibility issue:

* [EphemeralMongo6.runtime.ubuntu.22.04-x64](https://www.nuget.org/packages/EphemeralMongo6.runtime.ubuntu.22.04-x64)
* [EphemeralMongo7.runtime.ubuntu.22.04-x64](https://www.nuget.org/packages/EphemeralMongo7.runtime.ubuntu.22.04-x64)

I haven't updated the docs yet, but here's how to use them (example for MongoDB 6):

```xml
<PackageReference Include="EphemeralMongo.Core" Version="1.1.3" />
<PackageReference Include="EphemeralMongo6.runtime.ubuntu.22.04-x64" Version="1.1.3" Condition="$([MSBuild]::IsOSPlatform('Linux'))" />
<PackageReference Include="EphemeralMongo6.runtime.osx-x64" Version="1.1.3" Condition="$([MSBuild]::IsOSPlatform('OSX'))" />
<PackageReference Include="EphemeralMongo6.runtime.win-x64" Version="1.1.3" Condition="$([MSBuild]::IsOSPlatform('Windows'))" />
```

I'm planning to create a new package that would automatically download the right MongoDB version corresponding to the OS in use, at runtime, but that's for later. This would allow support for other architectures like ARM and reduce the number of EphemeralMongo versions published.
