### ISSUE TITLE
Support MongoDB 7

### ISSUE THREAD

**Issue by cptCloud** [asimmon/ephemeral-mongo#42]
MongoDB 7.0 just came out https://www.mongodb.com/blog/post/4-big-reasons-upgrade-mongodb-7-0. It requires the version 2.20 or higher for the driver first. They claimed massive query performance improvements.

**Comment by asimmon** [comment]
MongoDB 7.0.0 is now available with [EphemeralMongo7](https://www.nuget.org/packages/EphemeralMongo7/) and the MongoDB C# driver dependency has also been upgraded to support it.
