### ISSUE TITLE
.NET 8 Warning NETSDK1206 and not loading version/distribution specific lib *.ubuntu.22.04-x64

### ISSUE THREAD

**Issue by samuelnata-via** [asimmon/ephemeral-mongo#56]
I'm using the `<PackageReference Include="EphemeralMongo6.runtime.ubuntu.22.04-x64" Version="1.1.3" Condition="$([MSBuild]::IsOSPlatform('Linux'))" />` as mentioned in [#36](https://github.com/asimmon/ephemeral-mongo/issues/36) but my CI pipeline cant find the lib internal files. The pipeline runs on `mcr.microsoft.com/dotnet/sdk:8.0` image.

Bellow its the first error message on my pipeline:
`/usr/share/dotnet/sdk/8.0.300/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(284,5): warning NETSDK1206: Found version-specific or distribution-specific runtime identifier (s): ubuntu.22.04-x64. Affected libraries: EphemeralMongo6.runtime.ubuntu.22.04-x64. In .NET 8.0 and higher, assets for version-specific and distribution-specific runtime identifiers will not be found by default. See https://aka.ms/dotnet/rid-usage for details.`

As far as I understand, .NET 8 won't load this library because it has a specific distribution on its name, which causes a second error message:
`System.IO.FileNotFoundException : Could not find mongod in the following paths: '/github/workspace/tests/***.IntegrationTests/bin/Debug/net8.0/runtimes/linux-x64/native/mongodb/bin/ mongod'`

Maybe suffixing it with "linux-x64" would make .NET 8 build include this lib correctly for linux, but im not sure. Nobody had this error like me?

**Comment by samuelnata-via** [comment]
Actually the lib files are ben included, just not in the right folder, so the workarond proposed by @wcgomes in [#48](https://github.com/asimmon/ephemeral-mongo/issues/48) did the trick just by coping the file to the right folder. I will close this issue.

**Comment by 616b2f** [comment]
Do you mind to reopen it? Because we have the same issue.
